CREATE TABLE IF NOT EXISTS `employees` (
`id` INT NULL,
`name` VARCHAR(MAX) NULL,
`lastName` VARCHAR(MAX) NULL,
`role` VARCHAR(MAX) NULL,
`email` VARCHAR(MAX) NULL,
`gender` VARCHAR(MAX) NULL,
`country` VARCHAR(MAX) NULL,
`city` VARCHAR(MAX) NULL,
`state` VARCHAR(MAX) NULL,
`age` VARCHAR(MAX) NULL,
`phoneNumber` VARCHAR(MAX) NULL
);

INSERT INTO employees VALUES
(1,'Pau','García','Tech Lead','pau@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(2,'Alfredo','Rueda','Head Teacher','arueda@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(3,'Cristian','Fondevilla','Co-founder & CEO','cristian@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(4,'Daniel','Lucaci','Tech Lead','dani@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(5,'Alinne','Shedid','Talent & Partnerships Manager','alinne@assemblerschool.com','female','España','Barcelona','Cataluña',NULL,NULL),
(6,'Kasia','Adamowiczcr','Co-founder & COO','kasia@assemblerschool.com','female','España','Barcelona','Cataluña',NULL,NULL),
(7,'Alfredo','Narváez','Tech Lead','a.narvaez@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(8,'Manu','Sancho','Tech Lead','m.sancho@assemblerschool.com','male','España','Barcelona','Cataluña',NULL,NULL),
(9,'Anna','Troyán','Student','ana.troyan@gmail.com','female','España','Alicante','Comunidad Valenciana',NULL,NULL),
(10,'Verónica','Velázquez','Student','veronicavelazquezcalleja@gmail.com','female','España','Barcelona','Cataluña',NULL,NULL),
(11,'Miguel','García','Student','miguelgc_95@hotmail.com','male','España','Sevilla','Andalucía',NULL,NULL),
(12,'Yoguesh','Yadav','Student','aoyogesh78@yahoo.in','male','España','Barcelona','Cataluña',NULL,NULL),
(13,'Enric','Miró','Student','cirnemiro@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(14,'Irati','Arrieta','Student','irati.arrieta@hotmail.com','female','España','Irún','País Vasco',NULL,NULL),
(15,'Luis','Blanco','Student','leyber.91.2@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(16,'Cristina','Bulmes','Student','cristinabulnesmaya@gmail.com','female','España','Sevilla','Andalucía',NULL,NULL),
(17,'Marcel','Arie','Student','googlillo@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(18,'Ramón','Soler','Student','rsolerhernan@gmail.com','male','España','Valencia','Comunidad Valenciana',NULL,NULL),
(19,'Froilán','Olesti','Student','frolesti_9@hotmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(20,'Wilmer','Sierra','Student','wsierra010@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(21,'Victor','Greco','Student','victorgreco263@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(22,'Ignacio','Fernández','Student','ifernandezcerro@gmail.com','male','España','Madrid','Comunidad de Madrid',NULL,NULL),
(23,'Raúl','Cátedra','Student','raulcabe3003@gmail.com','male','España','Monachil','Andalucía',NULL,NULL),
(24,'Jan','Puig','Student','janpuigcapella@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(25,'Andres','Auais','Student','andresauais@gmail.com','male','España','Tenerife','Islas Canarias',NULL,NULL),
(26,'Fabrizio','Ervini','Student','Fabri.es018@gmail.com','male','España','Barcelona','Cataluña',NULL,NULL),
(27,'Jose','Serrano','Student','joseramonsr3@hotmail.com','male','España','Málaga','Andalucía',NULL,NULL),
(28,'Pablo','Caravaca','Student','pablocaravacacalvo.com','male','España','Sevilla','Andalucía',NULL,NULL),
(29,'Estefanía','Cordero','Student','estefania.cbrion@gmail.com','female','España','La Coruña','Galicia',NULL,NULL);